spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instagram?serverTimezone=Asia/Seoul
    username: user
    password: '1234'
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  jpa:
    hibernate:
      ddl-auto: update # <-- 매 서버 실행때마다 테이블이 삭제됬다가 다시 만들어짐 당연히 데이터 역시 날라감 하지만 테스트용으로 잠시 씀
    properties:
      hibernate:
        format_sql: true # <-- 실행쿼리를 가독성있게 표현
        show-sql: true # <-- 콘솔에 jpa 실행쿼리
    generate-ddl: true # < -- true로 설정 시, Entity 어노테이션(@Entity)이 명시된 클래스를 찾아서 ddl을 생성하고 실행